set: boundary
configs:
- config_id: cfg_data_w1_impl1_bypass0
  parameters:
    DATA_W: 1
    IMPL: 1
    BYPASS: 0
- config_id: cfg_data_w1024_impl1_bypass0
  parameters:
    DATA_W: 1024
    IMPL: 1
    BYPASS: 0
- config_id: cfg_data_w512_impl1_bypass0
  parameters:
    DATA_W: 512
    IMPL: 1
    BYPASS: 0
- config_id: cfg_data_w2_impl1_bypass0
  parameters:
    DATA_W: 2
    IMPL: 1
    BYPASS: 0
- config_id: cfg_data_w8_impl1_bypass0
  parameters:
    DATA_W: 8
    IMPL: 1
    BYPASS: 0
- config_id: cfg_data_w32_impl1_bypass0
  parameters:
    DATA_W: 32
    IMPL: 1
    BYPASS: 0
- config_id: cfg_data_w64_impl1_bypass0
  parameters:
    DATA_W: 64
    IMPL: 1
    BYPASS: 0
- config_id: cfg_data_w128_impl1_bypass0
  parameters:
    DATA_W: 128
    IMPL: 1
    BYPASS: 0
- config_id: cfg_data_w32_impl0_bypass0
  parameters:
    DATA_W: 32
    IMPL: 0
    BYPASS: 0
- config_id: cfg_data_w32_impl1_bypass1
  parameters:
    DATA_W: 32
    IMPL: 1
    BYPASS: 1
