set: boundary
configs:
- config_id: cfg_data_w2_id_impl0_seg_w4_cg_en1
  parameters:
    DATA_W: 2
    ID_IMPL: 0
    SEG_W: 4
    CG_EN: 1
- config_id: cfg_data_w1024_id_impl0_seg_w4_cg_en1
  parameters:
    DATA_W: 1024
    ID_IMPL: 0
    SEG_W: 4
    CG_EN: 1
- config_id: cfg_data_w513_id_impl0_seg_w4_cg_en1
  parameters:
    DATA_W: 513
    ID_IMPL: 0
    SEG_W: 4
    CG_EN: 1
- config_id: cfg_data_w3_id_impl0_seg_w4_cg_en1
  parameters:
    DATA_W: 3
    ID_IMPL: 0
    SEG_W: 4
    CG_EN: 1
- config_id: cfg_data_w8_id_impl0_seg_w4_cg_en1
  parameters:
    DATA_W: 8
    ID_IMPL: 0
    SEG_W: 4
    CG_EN: 1
- config_id: cfg_data_w16_id_impl0_seg_w4_cg_en1
  parameters:
    DATA_W: 16
    ID_IMPL: 0
    SEG_W: 4
    CG_EN: 1
- config_id: cfg_data_w32_id_impl0_seg_w4_cg_en1
  parameters:
    DATA_W: 32
    ID_IMPL: 0
    SEG_W: 4
    CG_EN: 1
- config_id: cfg_data_w64_id_impl0_seg_w4_cg_en1
  parameters:
    DATA_W: 64
    ID_IMPL: 0
    SEG_W: 4
    CG_EN: 1
- config_id: cfg_data_w32_id_impl1_seg_w4_cg_en1
  parameters:
    DATA_W: 32
    ID_IMPL: 1
    SEG_W: 4
    CG_EN: 1
- config_id: cfg_data_w32_id_impl0_seg_w2_cg_en1
  parameters:
    DATA_W: 32
    ID_IMPL: 0
    SEG_W: 2
    CG_EN: 1
- config_id: cfg_data_w32_id_impl0_seg_w16_cg_en1
  parameters:
    DATA_W: 32
    ID_IMPL: 0
    SEG_W: 16
    CG_EN: 1
- config_id: cfg_data_w32_id_impl0_seg_w9_cg_en1
  parameters:
    DATA_W: 32
    ID_IMPL: 0
    SEG_W: 9
    CG_EN: 1
- config_id: cfg_data_w32_id_impl0_seg_w3_cg_en1
  parameters:
    DATA_W: 32
    ID_IMPL: 0
    SEG_W: 3
    CG_EN: 1
- config_id: cfg_data_w32_id_impl0_seg_w8_cg_en1
  parameters:
    DATA_W: 32
    ID_IMPL: 0
    SEG_W: 8
    CG_EN: 1
- config_id: cfg_data_w32_id_impl0_seg_w4_cg_en0
  parameters:
    DATA_W: 32
    ID_IMPL: 0
    SEG_W: 4
    CG_EN: 0
