INPUT_WIDTH: 16
INPUT_SIGNED: true
COEFF: '45'
OUTPUT_MODE: FULL
SHIFT_RIGHT: 0
ROUND_MODE: FLOOR
OVERFLOW_MODE: WRAP
LATENCY: 2
IMPL: ADDER_GRAPH
OPERAND_ISOLATION: false
COEFF_WIDTH: 7
OUTPUT_SIGNED: true
OUTPUT_WIDTH: 22
