#!/usr/bin/env python3
"""Generate FuseSoC build metadata from the component's contract."""

import argparse
from pathlib import Path

import yaml

root = Path(__file__).resolve().parents[2]
ap = argparse.ArgumentParser()
ap.add_argument("--repair-dependency-build", action="store_true")
args = ap.parse_args()
if args.repair_dependency_build:
    dep = root.parent / "fixed_priority_arbiter/fusesoc/aixsilicon_cbb_fixed_priority_arbiter.core"
    dc = yaml.safe_load(dep.read_text())
    dc.pop("CAPI=2", None)
    dc.pop("provider", None)  # local source core, no downloadable provider
    for spec in dc["parameters"].values():
        spec["paramtype"] = "vlogparam"
    for name, target in dc["targets"].items():
        if name == "sim":
            target.pop(
                "parameters", None
            )  # existing fpa_tb has fixed internal instances, no parameters
            target.setdefault("tools", {})["vcs"] = {
                "vcs_options": ["-full64", "-timescale=1ns/1ps"]
            }
        else:
            target["parameters"] = list(dc["parameters"])
    dep.write_text(
        "CAPI=2:\n# Build metadata normalized by packet_locking_arbiter/verification/scripts/generate_core.py.\n"
        + yaml.safe_dump(dc, sort_keys=False, allow_unicode=True)
    )
meta = yaml.safe_load((root / "cbb.yaml").read_text())
params = {
    k: dict(
        datatype="int", paramtype="vlogparam", default=v["default"], description=v["description"]
    )
    for k, v in meta["parameters"].items()
}
core = dict(
    name=meta["release"]["fusesoc_core"],
    description=meta["purpose"]["summary"],
    filesets=dict(
        rtl=dict(
            files=["../rtl/packet_locking_arbiter.sv"],
            file_type="systemVerilogSource",
            depend=meta["implementations"][0]["dependencies"],
        ),
        example=dict(files=["../examples/packet_mux.sv"], file_type="systemVerilogSource"),
        tb=dict(files=["../verification/simulation/pla_tb.sv"], file_type="systemVerilogSource"),
        sdc=dict(files=["../constraints/packet_locking_arbiter.sdc"], file_type="SDC"),
    ),
    parameters=params,
    targets=dict(
        default=dict(filesets=["rtl"], toplevel="packet_locking_arbiter", parameters=list(params)),
        sim=dict(
            default_tool="vcs",
            filesets=["rtl", "example", "tb"],
            toplevel="pla_tb",
            parameters=list(params),
            tools=dict(vcs=dict(vcs_options=["-full64", "-timescale=1ns/1ps"])),
        ),
        synth=dict(
            filesets=["rtl", "sdc"], toplevel="packet_locking_arbiter", parameters=list(params)
        ),
        formal=dict(filesets=["rtl"], toplevel="packet_locking_arbiter", parameters=list(params)),
    ),
)
dest = root / "fusesoc/aixsilicon_cbb_packet_locking_arbiter.core"
dest.parent.mkdir(exist_ok=True)
dest.write_text(
    "CAPI=2:\n# Generated by verification/scripts/generate_core.py; do not edit.\n"
    + yaml.safe_dump(core, sort_keys=False, allow_unicode=True)
)
print(dest.name)
