"""Generate the standalone FuseSoC core from the component metadata."""

from pathlib import Path
import yaml

ROOT = Path(__file__).resolve().parents[1]


def main():
    meta = yaml.safe_load((ROOT / "cbb.yaml").read_text())["cbb"]
    core = {
        "name": meta["id"] + ":" + meta["version"],
        "filesets": {
            "rtl": {"files": ["rtl/constant_multiplier.sv"], "file_type": "systemVerilogSource"},
            "tb": {
                "files": ["verification/simulation/smoke_tb.sv"],
                "file_type": "systemVerilogSource",
            },
        },
        "targets": {
            "default": {"filesets": ["rtl"], "toplevel": "constant_multiplier"},
            "sim": {
                "default_tool": "vcs",
                "filesets": ["rtl", "tb"],
                "toplevel": "smoke_tb",
                "tools": {"vcs": {"vcs_options": ["-full64", "-sverilog", "-timescale=1ns/1ps"]}},
            },
        },
    }
    (ROOT / "constant_multiplier.core").write_text(
        "CAPI=2:\n# Generated by tools/package.py; do not edit.\n"
        + yaml.safe_dump(core, sort_keys=False)
    )


if __name__ == "__main__":
    main()
