set: boundary
configs:
- config_id: cfg_data_width1_depth16_output_regTrue
  parameters:
    DATA_WIDTH: 1
    DEPTH: 16
    OUTPUT_REG: true
- config_id: cfg_data_width1024_depth16_output_regTrue
  parameters:
    DATA_WIDTH: 1024
    DEPTH: 16
    OUTPUT_REG: true
- config_id: cfg_data_width512_depth16_output_regTrue
  parameters:
    DATA_WIDTH: 512
    DEPTH: 16
    OUTPUT_REG: true
- config_id: cfg_data_width2_depth16_output_regTrue
  parameters:
    DATA_WIDTH: 2
    DEPTH: 16
    OUTPUT_REG: true
- config_id: cfg_data_width8_depth16_output_regTrue
  parameters:
    DATA_WIDTH: 8
    DEPTH: 16
    OUTPUT_REG: true
- config_id: cfg_data_width32_depth16_output_regTrue
  parameters:
    DATA_WIDTH: 32
    DEPTH: 16
    OUTPUT_REG: true
- config_id: cfg_data_width64_depth16_output_regTrue
  parameters:
    DATA_WIDTH: 64
    DEPTH: 16
    OUTPUT_REG: true
- config_id: cfg_data_width128_depth16_output_regTrue
  parameters:
    DATA_WIDTH: 128
    DEPTH: 16
    OUTPUT_REG: true
- config_id: cfg_data_width32_depth2_output_regTrue
  parameters:
    DATA_WIDTH: 32
    DEPTH: 2
    OUTPUT_REG: true
- config_id: cfg_data_width32_depth4096_output_regTrue
  parameters:
    DATA_WIDTH: 32
    DEPTH: 4096
    OUTPUT_REG: true
- config_id: cfg_data_width32_depth2049_output_regTrue
  parameters:
    DATA_WIDTH: 32
    DEPTH: 2049
    OUTPUT_REG: true
- config_id: cfg_data_width32_depth3_output_regTrue
  parameters:
    DATA_WIDTH: 32
    DEPTH: 3
    OUTPUT_REG: true
- config_id: cfg_data_width32_depth4_output_regTrue
  parameters:
    DATA_WIDTH: 32
    DEPTH: 4
    OUTPUT_REG: true
- config_id: cfg_data_width32_depth8_output_regTrue
  parameters:
    DATA_WIDTH: 32
    DEPTH: 8
    OUTPUT_REG: true
- config_id: cfg_data_width32_depth16_output_regTrue
  parameters:
    DATA_WIDTH: 32
    DEPTH: 16
    OUTPUT_REG: true
- config_id: cfg_data_width32_depth64_output_regTrue
  parameters:
    DATA_WIDTH: 32
    DEPTH: 64
    OUTPUT_REG: true
- config_id: cfg_data_width32_depth256_output_regTrue
  parameters:
    DATA_WIDTH: 32
    DEPTH: 256
    OUTPUT_REG: true
- config_id: cfg_data_width32_depth1024_output_regTrue
  parameters:
    DATA_WIDTH: 32
    DEPTH: 1024
    OUTPUT_REG: true
