set: negative
configs:
- config_id: cfg_directionNARROW_TO_WIDE_narrow_width0_ratio4_depth8
  parameters:
    DIRECTION: NARROW_TO_WIDE
    NARROW_WIDTH: 0
    RATIO: 4
    DEPTH: 8
- config_id: cfg_directionNARROW_TO_WIDE_narrow_width513_ratio4_depth8
  parameters:
    DIRECTION: NARROW_TO_WIDE
    NARROW_WIDTH: 513
    RATIO: 4
    DEPTH: 8
- config_id: cfg_directionNARROW_TO_WIDE_narrow_width8_ratio1_depth8
  parameters:
    DIRECTION: NARROW_TO_WIDE
    NARROW_WIDTH: 8
    RATIO: 1
    DEPTH: 8
- config_id: cfg_directionNARROW_TO_WIDE_narrow_width8_ratio65_depth8
  parameters:
    DIRECTION: NARROW_TO_WIDE
    NARROW_WIDTH: 8
    RATIO: 65
    DEPTH: 8
- config_id: cfg_directionNARROW_TO_WIDE_narrow_width8_ratio4_depth1
  parameters:
    DIRECTION: NARROW_TO_WIDE
    NARROW_WIDTH: 8
    RATIO: 4
    DEPTH: 1
- config_id: cfg_directionNARROW_TO_WIDE_narrow_width8_ratio4_depth1025
  parameters:
    DIRECTION: NARROW_TO_WIDE
    NARROW_WIDTH: 8
    RATIO: 4
    DEPTH: 1025
