set: mandatory
configs:
- config_id: cfg_input_width16_input_signedTrue_coeff3_coeff_width128_output_mode0_round_mode0_overflow_mode0_impl0_output_width256_output_signedTrue_shift_right0_latency0_operand_isolationFalse
  parameters:
    INPUT_WIDTH: 16
    INPUT_SIGNED: true
    COEFF: 3
    COEFF_WIDTH: 128
    OUTPUT_MODE: 0
    ROUND_MODE: 0
    OVERFLOW_MODE: 0
    IMPL: 0
    OUTPUT_WIDTH: 256
    OUTPUT_SIGNED: true
    SHIFT_RIGHT: 0
    LATENCY: 0
    OPERAND_ISOLATION: false
  sets:
  - mandatory
  - boundary
  profiles:
  - profile_native
